# Generated by Django 6.0.6 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
    ]
